name: CI

on: push

jobs:
  build-and-test:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 10
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: build
    steps:
      - uses: actions/checkout@v3
        with:
          path: build
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Unit Test
        run: npm run coverage
      - name: Debug
        run: pwd && ls -la
      - name: Cleanup
        if: always()
        run: |
          pwd
          cd .. && rm -rf ./build

  sonarqube:
    runs-on: [self-hosted, linux, x64]
    timeout-minutes: 10
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: sonar
    steps:
      - uses: actions/checkout@v3
        with:
          path: sonar
      - name: Debug
        run: pwd && ls -la
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Unit Test
        run: npm run coverage
      - name: Sonarqube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          export SONAR_TOKEN
          export SONAR_HOST_URL
          /sonar/runsonar.sh
      - name: Debug
        run: pwd && ls -la ./.scannerwork/
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: /git/_work/graphiql-app/graphiql-app/sonar/.scannerwork/report-task.txt
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: 'Show SonarQube Quality Gate Status value'
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
      - name: Cleanup
        if: always()
        run: |
          pwd
          cd .. && rm -rf ./sonar

  deploy:
    runs-on: [self-hosted, linux, x64]
    needs: [build-and-test, sonarqube]
    if: |
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/develop/auto-deploy' ||
      github.ref == 'refs/heads/develop'
    steps:
      - name: Debug
        run: pwd && ls -la
      - name: Test
        run: |
          echo ${DEPLOY_REPO}
          echo ${{ secrets.GITHUB_TOKEN }}
